Naming file still not working
- diff against 018/prep comes clean. Must be missing a file or diff I'm not
seeing?

Current error:

> node bin/aws-s3-upload.js images/programmersLife.png multer-worked-i-think
inside crypto success 765c3a868665a674608c1b6a3d3a0998
TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.open (fs.js:631:11)
    at ReadStream.open (fs.js:1937:6)
    at new ReadStream (fs.js:1924:10)
    at Object.fs.createReadStream (fs.js:1871:10)
    at s3Upload (/Users/Benjamski/wdi-root/forge/training/multer/express-multer-project/lib/aws-upload.js:50:21)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
TypeError: Cannot read property 'Location' of undefined
    at awsUpload.then (/Users/Benjamski/wdi-root/forge/training/multer/express-multer-project/bin/aws-s3-upload.js:21:22)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)